name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  deploy_testing:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Deploy to Testing
      run: |
        # Add deployment script or commands to deploy to the testing environment
        echo "Deploying to Testing"

  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_testing
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/production'

    steps:
    - name: Deploy to Production
      run: |
        # Add deployment script or commands to deploy to the production environment
        echo "Deploying to Production"
